import type { Config } from "tailwindcss";
import defaultTheme from "tailwindcss/defaultTheme";
import {
  scopedPreflightStyles,
  isolateOutsideOfContainer,
} from "tailwindcss-scoped-preflight";

export default {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  plugins: [
    scopedPreflightStyles({
      isolationStrategy: isolateOutsideOfContainer(".no-tw"),
    }),
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Poppins", ...defaultTheme.fontFamily.sans],
      },
      typography: ({ theme }) => ({
        "amber-basic": {
          css: {
            "--tw-prose-body": theme("colors.amber[950]"),
            "--tw-prose-headings": theme("colors.amber[950]"),
            "--tw-prose-lead": theme("colors.amber[950]"),
            "--tw-prose-links": theme("colors.amber[950]"),
            "--tw-prose-bold": theme("colors.amber[950]"),
            "--tw-prose-counters": theme("colors.amber[950]"),
            "--tw-prose-bullets": theme("colors.amber[950]"),
            "--tw-prose-hr": theme("colors.amber[950]"),
            "--tw-prose-quotes": theme("colors.amber[950]"),
            "--tw-prose-quote-borders": theme("colors.amber[950]"),
            "--tw-prose-captions": theme("colors.amber[950]"),
            "--tw-prose-code": theme("colors.amber[950]"),
            "--tw-prose-pre-code": theme("colors.amber[950]"),
            "--tw-prose-pre-bg": theme("colors.amber[950]"),
            "--tw-prose-th-borders": theme("colors.amber[950]"),
            "--tw-prose-td-borders": theme("colors.amber[950]"),
            "--tw-prose-invert-body": theme("colors.amber[200]"),
            "--tw-prose-invert-headings": theme("colors.white"),
            "--tw-prose-invert-lead": theme("colors.amber[300]"),
            "--tw-prose-invert-links": theme("colors.white"),
            "--tw-prose-invert-bold": theme("colors.white"),
            "--tw-prose-invert-counters": theme("colors.amber[400]"),
            "--tw-prose-invert-bullets": theme("colors.amber[600]"),
            "--tw-prose-invert-hr": theme("colors.amber[700]"),
            "--tw-prose-invert-quotes": theme("colors.amber[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.amber[700]"),
            "--tw-prose-invert-captions": theme("colors.amber[400]"),
            "--tw-prose-invert-code": theme("colors.white"),
            "--tw-prose-invert-pre-code": theme("colors.amber[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.amber[600]"),
            "--tw-prose-invert-td-borders": theme("colors.amber[700]"),
          },
        },
        // "amber-default": {
        //   css: {
        //     "--tw-prose-body": theme("colors.amber[800]"),
        //     "--tw-prose-headings": theme("colors.amber[900]"),
        //     "--tw-prose-lead": theme("colors.amber[700]"),
        //     "--tw-prose-links": theme("colors.amber[900]"),
        //     "--tw-prose-bold": theme("colors.amber[900]"),
        //     "--tw-prose-counters": theme("colors.amber[600]"),
        //     "--tw-prose-bullets": theme("colors.amber[400]"),
        //     "--tw-prose-hr": theme("colors.amber[300]"),
        //     "--tw-prose-quotes": theme("colors.amber[900]"),
        //     "--tw-prose-quote-borders": theme("colors.amber[300]"),
        //     "--tw-prose-captions": theme("colors.amber[700]"),
        //     "--tw-prose-code": theme("colors.amber[900]"),
        //     "--tw-prose-pre-code": theme("colors.amber[100]"),
        //     "--tw-prose-pre-bg": theme("colors.amber[900]"),
        //     "--tw-prose-th-borders": theme("colors.amber[300]"),
        //     "--tw-prose-td-borders": theme("colors.amber[200]"),
        //     "--tw-prose-invert-body": theme("colors.amber[200]"),
        //     "--tw-prose-invert-headings": theme("colors.white"),
        //     "--tw-prose-invert-lead": theme("colors.amber[300]"),
        //     "--tw-prose-invert-links": theme("colors.white"),
        //     "--tw-prose-invert-bold": theme("colors.white"),
        //     "--tw-prose-invert-counters": theme("colors.amber[400]"),
        //     "--tw-prose-invert-bullets": theme("colors.amber[600]"),
        //     "--tw-prose-invert-hr": theme("colors.amber[700]"),
        //     "--tw-prose-invert-quotes": theme("colors.amber[100]"),
        //     "--tw-prose-invert-quote-borders": theme("colors.amber[700]"),
        //     "--tw-prose-invert-captions": theme("colors.amber[400]"),
        //     "--tw-prose-invert-code": theme("colors.white"),
        //     "--tw-prose-invert-pre-code": theme("colors.amber[300]"),
        //     "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
        //     "--tw-prose-invert-th-borders": theme("colors.amber[600]"),
        //     "--tw-prose-invert-td-borders": theme("colors.amber[700]"),
        //   },
        // },
      }),
    },
  },
} satisfies Config;
